In [11]:
import numpy as np 
A = np.array([[2,  -2 , 3 ], [1, 1, 1] , [1,3 ,-1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [12]:
#calculate eigenpairs 
values  , vectors = np.linalg.eig(A)
print(values)
print(vectors)

[ 3.  1. -2.]
[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [13]:
n = vectors[: ,1 ].T

In [14]:
np.linalg.norm(n)

1.0

In [15]:
# eigenvalues of diagonal matrix are the diagonal elements 
diag = np.array([[2, 0 , 0] , [0 , 1, 0] , [0 , 0 , - 1]])
values  , vectors = np.linalg.eig(diag)
print(vectors)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
