## Eigenvalues and eigenvectors

##### what are eigevalues and eigenvectors? 

- formal defination

let $A \in \mathbb{R}^{n \times n}$ ,we say that a non-zero vector $v \in \mathbb{R}^n $ is an eigenvector of A corresponding to eigenvalue $\lambda$(A Scalar) if 
$$ A\mathbf{v} = \lambda\mathbf{v}
$$ 



the above relation tell us that when the matrix(Linear transformation) 'A' is applied on v, then it scales v by amount $\lambda$
- Essentially we are trying to answer the question;  for a $n \times n$ matrix A , are there any directions such that when the matrix operates on these directions
 ,they maintain their orientation save for multiplication by Scalars(positive or negative)? 
- if so such directions are called eigenvectors and the scale factors are called eigenvalues




### calculating eigenvalues and eigenvectors using python

In [1]:
import numpy as np 
A = np.array([[2,  -2 , 3 ], [1, 1, 1] , [1,3,-1]]) # defining a matrix 
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [4]:
#Calculate eigenpairs(eigenvalues and eigenvectors) 
values , vectors = np.linalg.eig(A)
print(values) # eigenvalues

[ 3.  1. -2.]


In [8]:
print(vectors) 
# these are the eigenvectors, eigenvector corresponding to eigenvalue 3 is the first column in the below matrix  

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [11]:
#-->note: eigenvalues of diagonal matrix are the diagonal elements 
diag = np.array([[2, 0 , 0] , [0 , 1, 0] , [0 , 0 , - 1]])
values  , vectors = np.linalg.eig(diag)
print(values) # an array of diagonal elements 
print(vectors)

[ 2.  1. -1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### some uses of eigenvalues and eigenvectors

1.**Linear transformations**: Eigenvalues and eigenvectors can be used to understand and analyze linear transformations in fields such as physics, engineering, and computer graphics. Eigenvectors provide a basis for the transformation, and eigenvalues determine the scaling factor of each eigenvector.

2.**Principal component analysis (PCA)**: PCA is a technique used in data analysis to identify patterns in high-dimensional data. It uses eigenvalues and eigenvectors to transform the data into a new coordinate system where the data variance is maximized along the principal components.

3.**Image compression**: Eigenvalues and eigenvectors can be used to compress images by representing the image as a linear combination of the most significant eigenvectors. This reduces the size of the image file while preserving the most important features.